### ISSUE TITLE
Create "famKey" generator function

### ISSUE THREAD

**Issue by jessicajernigan** [shanemcf/famSpace#7]
## Purpose
On the back end, each "Fam" will be identified using a unique numeric id, but this won't be very pretty to users.

In order to ensure that the user-facing unique identifier is friendlier than "Garcia39943482", let's make it fun.

### Requirements
* Create a function that takes the user's input in the "create fam" step and appends positive adjectives
* Expected result: "WonderfulWilliamsFam" or "ThePeachyKeenMcMurtrys"

**Comment by josephptflanagan** [comment]
Complete as of 20200906@1320CDT
